CREATE TABLE Guesses (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, date TEXT NOT NULL, score INTEGER, show TEXT NOT NULL);
CREATE TABLE Users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password NOT NULL);
DELETE FROM Guesses WHERE id = 11;
COMMIT;
